import { Header } from '@/components/Header';
import { Hero } from '@/components/Hero';
import { ProblemSection } from '@/app/components/ProblemSection';
import { DifferentiationSection } from '@/app/components/DifferentiationSection';
import { HowItWorks } from '@/app/components/HowItWorks';
import { MarketOpportunity } from '@/app/components/MarketOpportunity';
import { PricingSection } from '@/app/components/PricingSection';
import { WaitlistSection } from '@/components/WaitlistSection';
import { Footer } from '@/components/F